#[build]
# https://github.com/rust-lang/rust/pull/124129
# https://github.com/dtolnay/linkme/pull/88
rustflags = ["-Z", "linker-features=-lld"]

[target.x86_64-unknown-linux-gnu]
linker = "clang-16"

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"
